// Generated from the source inventory; regenerate with scripts/schema.py.
export interface VetAccomodation { id: string; recId: number; branch_id: string; type: number; roomId: string; customerId?: string; patientsId?: string; checkinDate: string; checkOutDate: string; remark: string; isLogOut?: boolean; isArchive?: boolean; accomodationcheckOutId?: string; }
export interface VetAccomodationCheckOuts { id: string; recId: number; branch_id: string; accomodationId: string; checkinDate: string; checkOutDate: string; saleBuyId?: string; accomodationAmount: number; collectionAmount: number; paymentId: number; }
export interface VetAdress { id: string; recId: number; branch_id: string; province: string; district: string; county: string; longAdress: string; }
export interface VetAgenda { id: string; recId: number; branch_id: string; agendaNo?: number; agendaType?: number; isActive?: number; agendaTitle: string; priority?: number; dueDate?: string; notes: string; }
export interface VetAgendaTags { id: string; recId: number; branch_id: string; agendaId: string; tagsId?: string; tags: string; }
export interface VetAnimalBreedsDef { id: string; recId: number; branch_id: string; animalType: number; breedName: string; }
export interface VetAnimalColorsDef { id: string; recId: number; branch_id: string; name: string; }
export interface VetAnimalsType { id: string; recId: number; branch_id: string; type: number; name: string; description: string; }
export interface VetAppointmentTypes { id: string; recId: number; branch_id: string; type: number; remark: string; isChange: boolean; isDefaultPrice: boolean; price: number; taxisId?: string; colors: string; }
export interface VetAppoointments { id: string; recId: number; branch_id: string; beginDate: string; endDate: string; note: string; doctorId?: string; customerId?: string; patientsId?: string; appointmentType?: number; isCompleted?: boolean; vaccineId?: string; isPaymentReceived?: boolean; isMessage?: boolean; }
export interface VetCasingDefinition { id: string; recId: number; branch_id: string; caseName: string; active: boolean; kasa: string; durumu?: boolean; }
export interface VetCustomerGroupDef { id: string; recId: number; branch_id: string; code: string; name: string; }
export interface VetCustomers { id: string; recId: number; branch_id: string; firstName: string; lastName: string; phoneNumber: string; phoneNumber2: string; eMail: string; taxOffice: string; vKNTCNo: string; customerGroup?: string; note: string; discountRate: number; isEmail?: boolean; isPhone?: boolean; isArchive?: boolean; }
export interface VetDemandProducts { id: string; recId: number; branch_id: string; ownerId?: string; productId: string; quantity?: number; unitPrice?: number; amount?: number; stockState?: number; isActive?: number; reserved?: number; barcode: string; taxisId?: string; }
export interface VetDemands { id: string; recId: number; branch_id: string; date?: string; documentno: string; suppliers?: string; deliverydate?: string; note: string; state?: number; isBuying?: boolean; isAccounting?: boolean; iscomplated?: boolean; }
export interface VetDemandTrans { id: string; recId: number; branch_id: string; ownerId?: string; productId: string; quantity?: number; unitPrice?: number; amount?: number; stockState?: number; isActive?: number; reserved?: number; barcode: string; taxisId?: string; }
export interface VetDocuments { id: string; recId: number; branch_id: string; sourceId?: string; fileName: string; fileData: string; size: string; remark: string; }
export interface VetExamination { id: string; recId: number; branch_id: string; date: string; status: number; customerId: string; patientId: string; bodyTemperature: number; pulse: number; respiratoryRate: number; weight: number; symptoms: string; complaintStory: string; treatmentDescription: string; }
export interface VetFarms { id: string; recId: number; branch_id: string; customerId?: string; farmName: string; farmContact: string; farmRelationship: string; active?: boolean; }
export interface VetLabDocument { id: string; recId: number; branch_id: string; customerId: string; patientId: string; isRead?: boolean; fileName: string; fileData: string; remark: string; }
export interface VetLogs { id: string; recId: number; branch_id: string; date: string; userId: string; userName: string; oldValue: string; newValue: string; fieldName: string; tenantId: string; tableName: string; masterId: string; }
export interface VetMessageLogs { id: string; recId: number; branch_id: string; sendDate: string; userİd: string; customerId: string; content: string; itenrationType: number; integrationId: string; }
export interface VetParameters { id: string; recId: number; branch_id: string; appointmentReminderDuration?: number; agendaNoteReminder?: number; days: string; smsCompany?: string; cashAccount?: string; creditCardCashAccount?: string; bankTransferCashAccount?: string; whatsappTemplate?: string; customerWelcomeTemplate?: string; automaticAppointmentReminderMessageTemplate?: string; isOtoCustomerWelcomeMessage?: boolean; displayVetNo?: boolean; autoSms?: boolean; isAnimalsBreeds?: boolean; isFirstInspection?: boolean; appointmentBeginDate: string; appointmentEndDate: string; isExaminationAmuntZero?: boolean; datetimeStatus?: number; appointmentInterval?: number; appointmentSeansDuration?: number; petHotelsDateTimeFormat?: number; }
export interface VetPatients { id: string; recId: number; branch_id: string; customerId: string; name: string; birthDate: string; chipNumber?: string; sex: number; animalType?: number; animalBreed?: number; animalColor: number; reportNumber?: string; specialNote?: string; sterilization: boolean; images?: number; active?: boolean; isVaccineCalendarCreate?: boolean; }
export interface VetPaymentCollection { id: string; recId: number; branch_id: string; customerId?: string; collectionId?: string; date?: string; remark?: string; debit?: number; credit?: number; paid?: number; totalPaid?: number; total?: number; saleBuyId?: string; paymetntId?: number; }
export interface VetPaymentMethods { id: string; recId: number; branch_id: string; name: string; remark: string; }
export interface VetPrintTemplate { id: string; recId: number; branch_id: string; templateName: string; htmlContent: string; }
export interface VetProductCategories { id: string; recId: number; branch_id: string; name: string; categoryCode: string; }
export interface VetProductMovements { id: string; recId: number; branch_id: string; type: number; invoiceNo: string; date: string; totalAmount?: number; quantity: number; depotId: string; }
export interface VetProducts { id: string; recId: number; branch_id: string; name: string; productTypeId: number; unitId?: string; categoryId?: string; supplierId?: string; productBarcode: string; productCode: string; ratio: number; buyingPrice: number; sellingPrice: number; criticalAmount: number; active?: boolean; sellingIncludeKDV?: boolean; buyingIncludeKDV?: boolean; fixPrice?: boolean; isExpirationDate?: boolean; animalType?: number; numberRepetitions?: number; storeId: string; taxisId?: string; }
export interface VetRenewalOptions { id: string; recId: number; branch_id: string; remark: string; }
export interface VetReportFilter { id: string; recId: number; branch_id: string; enterprisesId: string; name: string; filterJson: string; }
export interface VetRooms { id: string; recId: number; branch_id: string; roomName: string; price: number; }
export interface VetSaleBuyOwner { id: string; recId: number; branch_id: string; type: number; customerId?: string; date: string; invoiceNo: string; paymentType: number; total?: number; discount?: number; kDV?: number; netPrice?: number; supplierId?: string; remark: string; demandsGuidId?: string; isAppointment?: boolean; appointmentId?: string; isExaminations?: boolean; examinationsId?: string; isAccomodation?: boolean; accomodationId?: string; }
export interface VetSaleBuyTrans { id: string; recId: number; branch_id: string; ownerId: string; productId?: string; ratio?: number; amount?: number; discount?: number; price?: number; netPrice?: number; invoiceNo: string; vatIncluded?: boolean; vatAmount?: number; orderId?: string; quantity: number; taxisId: string; isNew: boolean; }
export interface VetShortCuts { id: string; recId: number; branch_id: string; label: string; description: string; icon: string; link: string; useRouter: boolean; }
export interface VetSmsParameters { id: string; recId: number; branch_id: string; active: boolean; smsIntegrationType: number; userName: string; password: string; }
export interface VetSmsTemplate { id: string; recId: number; branch_id: string; active: boolean; name: string; content: string; enableSMS?: boolean; enableAppNotification?: boolean; enableEmail?: boolean; enableWhatsapp?: boolean; }
export interface VetStockTracking { id: string; recId: number; branch_id: string; productId: string; status: boolean; piece: number; usedPiece: number; remainingPiece: number; supplierId?: string; expirationDate?: string; salePrice?: number; purchasePrice?: number; unitId?: string; }
export interface VetStores { id: string; recId: number; branch_id: string; active: boolean; depotCode: string; depotName: string; }
export interface VetSuppliers { id: string; recId: number; branch_id: string; supplierName: string; email: string; phone: string; adress: string; companyName: string; mersisNo: string; webSite: string; taxOffice: string; taxNumber: string; active: boolean; }
export interface VetSymptoms { id: string; recId: number; branch_id: string; symptom: string; }
export interface VetTaxis { id: string; recId: number; branch_id: string; type: number; taxName: string; taxRatio: number; }
export interface VetUnits { id: string; recId: number; branch_id: string; unitCode: string; unitName: string; }
export interface VetVaccine { id: string; recId: number; branch_id: string; animalType: number; vaccineName: string; timeDone: number; obligation: number; totalSaleAmount?: number; }
export interface VetVaccineCalendar { id: string; recId: number; branch_id: string; animalType: number; vaccineDate: string; vaccinationDate?: string; isDone: boolean; isAdd: boolean; patientId: string; customerId: string; vaccineId: string; vaccineName: string; }
export interface VetVaccineMedicine { id: string; recId: number; branch_id: string; vaccineId: string; productId: string; quantity: number; salesAmount: number; taxisId: string; dosingType: number; remark: string; }
export interface VetWeightControl { id: string; recId: number; branch_id: string; patientId: string; weight: number; controlDate: string; }