import {Component,OnInit} from '@angular/core';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {ClinicClientService} from 'app/core/supabase/clinic-client.service';
@Component({selector:'app-clinic-team',standalone:true,imports:[CommonModule,FormsModule],template:`<section class="w-full"><h2 class="text-2xl font-bold">Klinik Ekibi</h2><p class="my-4" role="status">{{message}}</p><form (ngSubmit)="invite()" class="flex flex-wrap gap-4 my-6"><label>Ad<input class="block border p-2" name="name" [(ngModel)]="name" required maxlength="120"></label><label>E-posta<input class="block border p-2" name="email" type="email" [(ngModel)]="email" required></label><label>Rol<select class="block border p-2" name="role" [(ngModel)]="role"><option *ngFor="let r of roles" [value]="r.code">{{r.name}}</option></select></label><label>Şube<select class="block border p-2" name="branch" [(ngModel)]="branch" required><option *ngFor="let b of branches" [value]="b.id">{{b.name}}</option></select></label><button class="border p-3" [disabled]="busy">Davet et</button></form><p class="my-4">Veteriner klinik kayıtlarını; resepsiyon müşteri ve randevuları; muhasebe satış ve stok işlemlerini yönetir. Okuyucu rolü kayıt değiştiremez. Klinik sahibi tüm şubelere erişir.</p><table class="w-full"><thead><tr><th>Ad</th><th>E-posta</th><th>Rol</th><th>Şube</th><th>Aktif</th><th></th></tr></thead><tbody><tr *ngFor="let u of members"><td><input aria-label="Üye adı" class="border p-2" [(ngModel)]="u.name"></td><td>{{u.email}}</td><td><select aria-label="Üye rolü" class="border p-2" [(ngModel)]="u.role"><option value="owner">Klinik sahibi</option><option *ngFor="let r of roles" [value]="r.code">{{r.name}}</option></select></td><td><select aria-label="Üye şubesi" class="border p-2" [(ngModel)]="u.branch_id"><option *ngFor="let b of branches" [value]="b.id">{{b.name}}</option></select></td><td><input type="checkbox" aria-label="Aktif üye" [(ngModel)]="u.active"></td><td><button class="border p-2" [disabled]="busy" (click)="save(u)">Kaydet</button></td></tr></tbody></table></section>`})
export class ClinicTeamComponent implements OnInit {
 members:any[]=[];branches:any[]=[];name='';email='';role='vet';branch='';message='';busy=false;
 roles=[{code:'vet',name:'Veteriner'},{code:'reception',name:'Resepsiyon'},{code:'accountant',name:'Muhasebe'},{code:'reader',name:'Okuyucu'}];constructor(private clinics:ClinicClientService){}
 async ngOnInit(){await this.refresh();}
 async refresh(){try{const db=await this.clinics.client();const profile=await this.clinics.loadProfile();if(profile.role!=='owner')throw new Error('Bu ekran klinik sahibine açıktır.');const members=await db.from('profiles').select('*').order('name');if(members.error)throw members.error;const branches=await db.from('branches').select('*').eq('active',true);if(branches.error)throw branches.error;this.members=members.data;this.branches=branches.data;this.branch=this.branch||profile.branch_id;}catch(e){this.message=e.message;}}
 async invite(){this.busy=true;try{const {error}=await(await this.clinics.client()).functions.invoke('clinic-members',{body:{email:this.email,name:this.name,role:this.role,branch_id:this.branch}});if(error)throw error;this.message='Üyelik hazırlandı. Yeni kullanıcı e-posta davetiyle şifresini belirleyebilir.';this.email='';this.name='';await this.refresh();}catch(e){this.message=e.message;}finally{this.busy=false;}}
 async save(u:any){this.busy=true;try{const {error}=await(await this.clinics.client()).rpc('update_member',{p_id:u.id,p_name:u.name,p_role:u.role,p_branch:u.branch_id,p_active:u.active});if(error)throw error;this.message='Üyelik güncellendi.';await this.refresh();}catch(e){this.message=e.message;}finally{this.busy=false;}}
}
