import {Component,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {ActivatedRoute,Router,RouterModule} from '@angular/router';
import {ClinicClientService} from 'app/core/supabase/clinic-client.service';
@Component({selector:'app-callback',standalone:true,imports:[CommonModule,FormsModule,RouterModule],template:`<main class="max-w-lg mx-auto p-8"><h1 class="text-3xl font-bold">Odivon Vet hesabınız</h1><p role="status" class="my-4">{{message}}</p><form *ngIf="ready" (ngSubmit)="save()"><label class="block">Yeni şifre<input class="block border p-3 w-full" type="password" name="password" autocomplete="new-password" minlength="12" required [(ngModel)]="password"></label><label class="block my-4">Şifreyi doğrula<input class="block border p-3 w-full" type="password" name="confirm" autocomplete="new-password" required [(ngModel)]="confirm"></label><button class="p-3 border" [disabled]="busy">Şifreyi kaydet ve kliniğe gir</button></form><a class="block my-4 underline" routerLink="/auth/sign-in">Giriş ekranı</a></main>`})
export class CallbackComponent implements OnInit {
 message='Bağlantı doğrulanıyor…';ready=false;busy=false;password='';confirm='';
 constructor(private clinics:ClinicClientService,private route:ActivatedRoute,private router:Router){}
 async ngOnInit(){try{const code=this.route.snapshot.queryParamMap.get('clinic');const db=await this.clinics.connect(code);const {data,error}=await db.auth.getSession();if(error||!data.session)throw new Error('Bağlantı geçersiz veya süresi dolmuş. Yeni davet veya şifre yenileme bağlantısı alın.');const user=await db.auth.getUser();if(user.error)throw user.error;this.ready=true;this.message='Hesabınızı kullanmak için şifrenizi belirleyin.';}catch(e){this.message=e.message;}}
 async save(){if(this.password.length<12||this.password!==this.confirm){this.message='En az 12 karakter girin; şifreler aynı olmalı.';return;}this.busy=true;try{const {error}=await(await this.clinics.client()).auth.updateUser({password:this.password});if(error)throw error;await this.clinics.loadProfile();await this.router.navigateByUrl('/dashboards');}catch(e){this.message=e.message;}finally{this.busy=false;}}
}
