from pathlib import Path
root=Path(__file__).resolve().parents[1]
def write(path,s):(root/path).write_text(s,encoding='utf-8')
for name,path in [('reports','src/app/modules/admin/reports'),('sms','src/app/modules/admin/sms'),('checkportfolio','src/app/modules/admin/cashing/checkportfolio')]:
 p=root/path/(name+'.module.ts');s=p.read_text();s="import {CommonModule} from '@angular/common';\n"+s if 'import {CommonModule}' not in s and 'import { CommonModule }' not in s else s;s=s.replace('imports     : [','imports     : [\n        CommonModule,');p.write_text(s)
write('src/app/modules/admin/reports/reports.component.ts','''import {Component} from '@angular/core';import {ClinicClientService} from 'app/core/supabase/clinic-client.service';
@Component({selector:'app-reports',templateUrl:'./reports.component.html'})
export class ReportsComponent{kind='sales';from=new Date().toISOString().slice(0,7)+'-01';to=new Date().toISOString().slice(0,10);branch='';rows:any[]=[];columns:string[]=[];branches:any[]=[];error='';busy=false;
 constructor(private clinics:ClinicClientService){this.loadBranches();}async loadBranches(){try{const {data,error}=await (await this.clinics.client()).from('branches').select('*');if(error)throw error;this.branches=data;}catch(e){this.error=e.message;}}
 async load(){this.busy=true;this.error='';try{const {data,error}=await (await this.clinics.client()).rpc('clinic_report',{p_kind:this.kind,p_from:this.from,p_to:this.to,p_branch:this.branch||null});if(error)throw error;this.rows=data;this.columns=data.length?Object.keys(data[0]):[];}catch(e){this.error=e.message;}finally{this.busy=false;}}
 csv(){const cell=(v:any)=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const text=[this.columns,...this.rows.map(r=>this.columns.map(c=>r[c]))].map(r=>r.map(cell).join(';')).join('\\r\\n');const url=URL.createObjectURL(new Blob(['\\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='odivon-'+this.kind+'.csv';a.click();URL.revokeObjectURL(url);}
 print(){window.print();}}
''')
write('src/app/modules/admin/reports/reports.component.html','''<main class="p-8 w-full"><h1 class="text-3xl font-bold">Raporlar</h1><form class="flex flex-wrap gap-4 my-6" (ngSubmit)="load()"><label>Rapor<select class="block border p-2" name="kind" [(ngModel)]="kind"><option value="sales">Satış / alış</option><option value="collections">Tahsilat</option><option value="stock">Stok</option><option value="appointments">Randevu</option></select></label><label>Başlangıç<input class="block border p-2" type="date" name="from" [(ngModel)]="from" required></label><label>Bitiş<input class="block border p-2" type="date" name="to" [(ngModel)]="to" required></label><label>Şube<select class="block border p-2" name="branch" [(ngModel)]="branch"><option value="">Yetkili olduğum şubeler</option><option *ngFor="let b of branches" [value]="b.id">{{b.name}}</option></select></label><button class="border p-3" [disabled]="busy">Raporu getir</button></form><p role="alert">{{error}}</p><div class="flex gap-4 my-4"><button class="border p-2" [disabled]="!rows.length" (click)="csv()">CSV indir</button><button class="border p-2" [disabled]="!rows.length" (click)="print()">Yazdır / PDF kaydet</button></div><p *ngIf="!rows.length && !busy">Seçilen aralıkta kayıt bulunmuyor.</p><div class="overflow-auto"><table class="w-full bg-card"><thead><tr><th class="p-3 text-left border-b" *ngFor="let c of columns">{{c}}</th></tr></thead><tbody><tr *ngFor="let r of rows"><td class="p-3 border-b" *ngFor="let c of columns">{{r[c]}}</td></tr></tbody></table></div></main>''')
write('src/app/modules/admin/sms/sms.component.ts','''import {Component,OnInit} from '@angular/core';import {ClinicClientService} from 'app/core/supabase/clinic-client.service';
@Component({selector:'app-sms',templateUrl:'./sms.component.html'})
export class SmsComponent implements OnInit{recipients='';body='';templates:any[]=[];template='';rows:any[]=[];message='';busy=false;private requestKey='';private requestFingerprint='';constructor(private clinics:ClinicClientService){}async ngOnInit(){await this.refresh();try{const {data}=await (await this.clinics.client()).from('vetsmstemplate').select('*');this.templates=data||[];}catch{}}
 useTemplate(){const t=this.templates.find(t=>t.id===this.template);if(t)this.body=t.message||t.content||t.template||t.smsContent||'';}
 async refresh(){try{const {data,error}=await (await this.clinics.client()).from('message_outbox').select('*').eq('channel','sms').order('created_at',{ascending:false}).limit(100);if(error)throw error;this.rows=data;}catch(e){this.message=e.message;}}
 async send(){this.busy=true;try{const recipients=Array.from(new Set(this.recipients.split(/[\\s,;]+/).map(v=>v.trim()).filter(Boolean)));const fingerprint=JSON.stringify({recipients,body:this.body});if(this.requestFingerprint!==fingerprint){this.requestKey=crypto.randomUUID();this.requestFingerprint=fingerprint;}const {error}=await (await this.clinics.client()).rpc('enqueue_message',{p_channel:'sms',p_recipients:recipients,p_subject:'',p_body:this.body,p_key:this.requestKey});if(error)throw error;this.message='Mesajlar gönderim kuyruğuna alındı.';this.body='';this.requestKey='';this.requestFingerprint='';await this.refresh();}catch(e){this.message=e.message;}finally{this.busy=false;}}
}
''')
write('src/app/modules/admin/sms/sms.component.html','''<main class="p-8 w-full"><h1 class="text-3xl font-bold">SMS İşlemleri</h1><p role="status" class="my-4">{{message}}</p><form (ngSubmit)="send()" class="max-w-2xl"><label class="block my-4">Şablon<select class="block border p-3 w-full" name="template" [(ngModel)]="template" (change)="useTemplate()"><option value="">Şablon seç</option><option *ngFor="let t of templates" [value]="t.id">{{t.name || t.title}}</option></select></label><label class="block my-4">Telefonlar (virgülle ayırın)<textarea class="block border p-3 w-full" name="recipients" [(ngModel)]="recipients" required></textarea></label><label class="block my-4">Mesaj<textarea class="block border p-3 w-full" rows="4" name="body" [(ngModel)]="body" maxlength="10000" required></textarea></label><button class="border p-3" [disabled]="busy">Gönderim kuyruğuna al</button></form><div class="flex gap-4 my-6"><h2 class="text-xl font-bold">Gönderim geçmişi</h2><button class="border px-3" (click)="refresh()">Yenile</button></div><table class="w-full bg-card"><thead><tr><th>Alıcı</th><th>Mesaj</th><th>Durum</th><th>Tarih</th></tr></thead><tbody><tr *ngFor="let r of rows"><td class="p-3">{{r.recipient}}</td><td class="p-3">{{r.body}}</td><td class="p-3">{{r.state}} {{r.safe_error}}</td><td class="p-3">{{r.created_at | date:'short'}}</td></tr></tbody></table></main>''')
write('src/app/modules/admin/cashing/checkportfolio/checkportfolio.component.ts','''import {Component,OnInit} from '@angular/core';import {ClinicClientService} from 'app/core/supabase/clinic-client.service';
@Component({selector:'app-checkportfolio',templateUrl:'./checkportfolio.component.html'})
export class CheckportfolioComponent implements OnInit{rows:any[]=[];form:any={number:'',bank:'',amount:null,due_date:'',status:'portfolio',note:''};message='';busy=false;constructor(private clinics:ClinicClientService){}async ngOnInit(){await this.load();}async load(){try{const {data,error}=await (await this.clinics.client()).from('cheques').select('*').order('due_date');if(error)throw error;this.rows=data;}catch(e){this.message=e.message;}}edit(row:any){this.form={...row};}async save(){this.busy=true;try{const {error}=await (await this.clinics.client()).rpc('save_cheque',{p_data:this.form});if(error)throw error;this.form={number:'',bank:'',amount:null,due_date:'',status:'portfolio',note:''};this.message='Kaydedildi';await this.load();}catch(e){this.message=e.message;}finally{this.busy=false;}}}
''')
write('src/app/modules/admin/cashing/checkportfolio/checkportfolio.component.html','''<main class="p-8 w-full"><h1 class="text-3xl font-bold">Çek Portföyü</h1><p role="status" class="my-4">{{message}}</p><form class="flex flex-wrap gap-4 my-6" (ngSubmit)="save()"><label>Çek no<input class="block border p-3" name="number" [(ngModel)]="form.number" required></label><label>Banka<input class="block border p-3" name="bank" [(ngModel)]="form.bank"></label><label>Tutar<input class="block border p-3" type="number" min="0.01" step="0.01" name="amount" [(ngModel)]="form.amount" required></label><label>Vade<input class="block border p-3" type="date" name="due" [(ngModel)]="form.due_date" required></label><label>Durum<select class="block border p-3" name="status" [(ngModel)]="form.status"><option value="portfolio">Portföyde</option><option value="deposited">Bankaya verildi</option><option value="collected">Tahsil edildi</option><option value="returned">İade</option><option value="cancelled">İptal</option></select></label><button class="border p-3" [disabled]="busy">Kaydet</button></form><table class="w-full bg-card"><thead><tr><th>No</th><th>Banka</th><th>Tutar</th><th>Vade</th><th>Durum</th><th>İşlem</th></tr></thead><tbody><tr *ngFor="let r of rows"><td class="p-3">{{r.number}}</td><td>{{r.bank}}</td><td>{{r.amount | number:'1.2-2'}}</td><td>{{r.due_date | date:'shortDate'}}</td><td>{{r.status}}</td><td><button (click)="edit(r)" [disabled]="r.status==='collected'||r.status==='cancelled'">Düzenle</button></td></tr></tbody></table></main>''')
