from pathlib import Path
r=Path(__file__).resolve().parents[1]
(r/'src/app/core/services/lab/lab.service.ts').write_text('''import {Injectable} from '@angular/core';import {defer,Observable} from 'rxjs';import {ClinicClientService} from 'app/core/supabase/clinic-client.service';import {VetDataService} from 'app/core/supabase/vet-data.service';
@Injectable({providedIn:'root'})export class LabService {constructor(private clinics:ClinicClientService,private data:VetDataService){}getCustomersLabList():Observable<any>{return defer(()=>this.data.execute('vet/Customers/CustomersList',{}));}getLabDocumentById(model:any):Observable<any>{return defer(async()=>{const {data,error}=await(await this.clinics.client()).rpc('lab_details',{p_patient:model.PatientId||model.patientId});if(error)throw error;return {data,isSuccessful:true};});}}
''',encoding='utf-8')
p=r/'src/app/modules/admin/patient/lab/labuploaddocument/labuploaddocument.component.ts'
p.write_text('''import {Component,Inject} from '@angular/core';import {MAT_DIALOG_DATA,MatDialogRef} from '@angular/material/dialog';import {ClinicFilesService} from 'app/core/supabase/clinic-files.service';
@Component({selector:'app-labuploaddocument',templateUrl:'./labuploaddocument.component.html',styleUrls:['./labuploaddocument.component.css']})
export class LabuploaddocumentComponent {file:File;message='';buttonDisabled=false;private id=crypto.randomUUID();constructor(private dialog:MatDialogRef<any>,private files:ClinicFilesService,@Inject(MAT_DIALOG_DATA)private data:{patientId:string;customerId:string}){}onChange(event:Event){this.file=(event.target as HTMLInputElement).files?.[0];this.id=crypto.randomUUID();}closeDialog(){this.dialog.close({status:false});}async addOrUpdateDocument(){if(!this.file)return;this.buttonDisabled=true;try{await this.files.upload(this.file,this.id,this.data.patientId,this.data.customerId,'lab');this.dialog.close({status:true});}catch(e){this.message=e.message;}finally{this.buttonDisabled=false;}}}
''',encoding='utf-8')
p=r/'src/app/modules/admin/patient/lab/labuploaddocument/labuploaddocument.component.html';p.write_text('''<h2 mat-dialog-title>Laboratuvar dosyası yükle</h2><mat-dialog-content><p role="alert">{{message}}</p><label>Dosya<input type="file" (change)="onChange($event)"></label><p *ngIf="file">{{file.name}} · {{file.size}} bayt</p></mat-dialog-content><mat-dialog-actions><button mat-button (click)="closeDialog()">Vazgeç</button><button mat-flat-button color="primary" [disabled]="buttonDisabled || !file" (click)="addOrUpdateDocument()">Yükle</button></mat-dialog-actions>''',encoding='utf-8')
p=r/'src/app/modules/admin/patient/lab/labdetails/labdetails.component.ts';s=p.read_text(encoding='utf-8');s="import {ClinicFilesService} from 'app/core/supabase/clinic-files.service';\n"+s;s=s.replace('    private route: ActivatedRoute,','    private files:ClinicFilesService,\n    private route: ActivatedRoute,')
a=s.index('  downloadDocument(');b=s.index('  openFileUpload()',a);s=s[:a]+'''  async downloadDocument(file:LabDocumentDto):Promise<void> {try{const blob=await this.files.download(file.documentId);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=file.documentName;a.click();URL.revokeObjectURL(url);}catch(e){this.error=e.message;}}
  error='';
'''+s[b:]
s=s.replace('data: null,','data: {patientId:this.patientId,customerId:this.labdocumentdto.customerId},');s=s.replace('if (response.status)', 'if (response?.status)');p.write_text(s,encoding='utf-8')
p=r/'src/app/modules/admin/patient/lab/labdetails/labdetails.component.html';s=p.read_text(encoding='utf-8');s=s[s.index('<div class="flex flex-col flex-auto min-w-0">',s.index('-->')):];s='<p role="alert">{{error}}</p>'+s;s=s.replace('labdocumentdto.','labdocumentdto?.').replace('document.name','document.documentName').replace('document.date','document.documentDate');p.write_text(s,encoding='utf-8')
