from pathlib import Path
r=Path(__file__).resolve().parents[1]
(r/'src/app/modules/admin/provider-settings/provider-settings.component.ts').write_text('''import {Component,OnInit} from '@angular/core';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {ClinicClientService} from 'app/core/supabase/clinic-client.service';
@Component({selector:'app-provider-settings',standalone:true,imports:[CommonModule,FormsModule],template:`<section class="max-w-3xl"><h2 class="text-2xl font-bold">SMS ve E-posta Bağlantıları</h2><p role="status" class="my-4">{{message}}</p><p class="my-4">{{status?.mode==='test'?'Test modu: gerçek SMS veya e-posta gönderilmez.':'Canlı gönderim modu'}} · SMS {{status?.smsConfigured?'yapılandırılmış':'bekliyor'}} · E-posta {{status?.emailConfigured?'yapılandırılmış':'bekliyor'}}</p><form (ngSubmit)="save()"><label>Çalışma modu<select class="block border p-2 my-2" name="mode" [(ngModel)]="mode"><option value="test">Test sağlayıcısı</option><option value="live">Gerçek gönderim</option></select></label><h3 class="text-xl font-bold mt-6">Mutlucell SMS</h3><label class="block my-3">Kullanıcı adı<input class="block border p-2 w-full" name="smsUser" [(ngModel)]="sms.user" autocomplete="off"></label><label class="block my-3">API şifresi<input class="block border p-2 w-full" name="smsPassword" type="password" [(ngModel)]="sms.password" autocomplete="new-password"></label><label class="block my-3">Onaylı gönderici başlığı<input class="block border p-2 w-full" name="smsSender" [(ngModel)]="sms.sender"></label><h3 class="text-xl font-bold mt-6">Resend E-posta</h3><label class="block my-3">API anahtarı<input class="block border p-2 w-full" name="emailKey" type="password" [(ngModel)]="email.key" autocomplete="new-password"></label><label class="block my-3">Doğrulanmış gönderici adresi<input class="block border p-2 w-full" type="email" name="emailFrom" [(ngModel)]="email.from"></label><p class="my-4">Kaydedilmiş anahtarlar gösterilmez. Boş bıraktığınız bağlantı alanları önceki değerlerini korur.</p><button class="border p-3" [disabled]="busy">Bağlantıları kaydet</button></form></section>`})
export class ProviderSettingsComponent implements OnInit{status:any;message='';mode='test';sms={user:'',password:'',sender:''};email={key:'',from:''};busy=false;constructor(private clinics:ClinicClientService){}async ngOnInit(){try{const {data,error}=await(await this.clinics.client()).rpc('provider_status');if(error)throw error;this.status=data;this.mode=data.mode;}catch(e){this.message=e.message;}}async save(){this.busy=true;try{const {error}=await(await this.clinics.client()).rpc('set_provider_configuration',{p_data:{mode:this.mode,sms:this.sms,email:this.email}});if(error)throw error;this.sms={user:'',password:'',sender:''};this.email={key:'',from:''};await this.ngOnInit();this.message='Bağlantılar kaydedildi.';}catch(e){this.message=e.message;}finally{this.busy=false;}}}
''',encoding='utf-8')
p=r/'src/app/modules/admin/generalsettings/generalsettings.module.ts';s=p.read_text(encoding='utf-8');s="import {ProviderSettingsComponent} from '../provider-settings/provider-settings.component';\n"+s;s=s.replace('imports: [','imports: [ProviderSettingsComponent,');p.write_text(s,encoding='utf-8')
p=r/'src/app/modules/admin/generalsettings/generalsettings.component.html';s=p.read_text(encoding='utf-8').replace('<app-mailing></app-mailing>','<app-provider-settings></app-provider-settings>').replace('<app-smslog></app-smslog>','<a class="underline" routerLink="/sms">SMS gönderimi ve teslim geçmişini aç</a>');p.write_text(s,encoding='utf-8')
p=r/'src/app/app.routing.ts';s=p.read_text(encoding='utf-8');s=s.replace("export const appRoutes: Route[] = [","export const appRoutes: Route[] = [\n {path:'smsparameters',canActivate:[AuthGuard],loadComponent:()=>import('app/modules/admin/provider-settings/provider-settings.component').then(m=>m.ProviderSettingsComponent)},");p.write_text(s,encoding='utf-8')
p=r/'src/app/modules/admin/sms/sms.component.ts';s=p.read_text(encoding='utf-8').replace("recipients='';","mode='test';recipients='';");s=s.replace('await this.refresh();try{','await this.refresh();try{const status=await(await this.clinics.client()).rpc(\'provider_status\');if(status.error)throw status.error;this.mode=status.data.mode;');p.write_text(s,encoding='utf-8')
p=r/'src/app/modules/admin/sms/sms.component.html';s=p.read_text(encoding='utf-8').replace('</h1>','</h1><p class="my-4" *ngIf="mode===\'test\'">Test modu: gerçek mesaj gönderilmez. Canlı gönderim Genel Ayarlar üzerinden açılır.</p>',1).replace('{{r.state}}','{{r.provider_id?.startsWith(\'test-\') ? \'Test tamamlandı\' : r.state}}');p.write_text(s,encoding='utf-8')
p=r/'src/app/modules/admin/commonscreen/message-send/message-send.component.html';s=p.read_text(encoding='utf-8');import re;s=re.sub(r'<mat-slide-toggle[^>]*formControlName="(?:enableAppNotification|enableWhatsapp)"[^>]*>.*?</mat-slide-toggle>','',s,flags=re.S);p.write_text(s,encoding='utf-8')
