from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=root/'src/app/modules/auth/registration/registration.component.ts'
p.write_text('''import {Component,OnInit} from '@angular/core';import {CommonModule} from '@angular/common';import {FormsModule} from '@angular/forms';import {RouterModule} from '@angular/router';import {ClinicClientService} from 'app/core/supabase/clinic-client.service';
@Component({selector:'app-registration',standalone:true,imports:[CommonModule,FormsModule,RouterModule],template:`<main class="p-8 max-w-xl mx-auto"><h1 class="text-3xl font-bold">Odivon Vet</h1><h2 class="text-xl my-4">Klinik başvurusu</h2><p role="status">{{message}}</p><form *ngIf="!application" (ngSubmit)="submit()"><label class="block mt-4">Klinik adı<input class="block border p-3 w-full" name="name" [(ngModel)]="name" required maxlength="120"></label><label class="block mt-4">Klinik kodu<input class="block border p-3 w-full" name="code" [(ngModel)]="code" required pattern="[a-z0-9][a-z0-9-]{2,47}" placeholder="ornek-klinik"></label><label class="block mt-4">Ad soyad<input class="block border p-3 w-full" name="owner" [(ngModel)]="owner" required></label><ng-container *ngIf="!verified"><label class="block mt-4">E-posta<input class="block border p-3 w-full" name="email" [(ngModel)]="email" type="email" required></label><label class="block mt-4">Parola<input class="block border p-3 w-full" name="password" [(ngModel)]="password" type="password" minlength="12" required autocomplete="new-password"></label><div id="registration-captcha" class="my-4"></div></ng-container><button class="border p-3 my-4 bg-primary text-white" [disabled]="busy">{{verified?'Kliniğimi oluştur':'E-postamı doğrula'}}</button></form><section *ngIf="application"><p class="my-4">Klinik kodu: <strong>{{application.code}}</strong></p><p>{{stateLabel(application.state)}}</p><button class="border p-3 my-4" (click)="refresh()" [disabled]="busy">Durumu yenile</button><p *ngIf="application.state==='ready'">Klinik hesabınızı oluşturmak için e-postanıza gönderilen daveti açın. Deneme süreniz 14 gündür.</p></section><a routerLink="/auth/sign-in" class="block underline">Klinik girişine dön</a></main>`})
export class RegistrationComponent implements OnInit{
 name='';code='';owner='';email='';password='';message='';busy=false;verified=false;application:any;captchaToken='';
 constructor(private clinics:ClinicClientService){}
 async ngOnInit(){try{const client=await this.clinics.management();const {data:{user}}=await client.auth.getUser();this.verified=!!user?.email_confirmed_at;if(user){const m=user.user_metadata;this.name=m.clinic_name||'';this.code=m.clinic_code||'';this.owner=m.owner_name||'';await this.refresh();}else{const config:any=await this.clinics.config();if(config.turnstileSiteKey){await this.loadCaptcha(config.turnstileSiteKey);}}}catch(e){this.message=e.message;}}
 async loadCaptcha(siteKey:string){const w=window as any;const render=()=>w.turnstile.render('#registration-captcha',{sitekey:siteKey,callback:(token:string)=>this.captchaToken=token,'expired-callback':()=>this.captchaToken=''});if(w.turnstile){render();return;}const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=render;script.onerror=()=>this.message='Doğrulama yüklenemedi; sayfayı yenileyin.';document.head.appendChild(script);}
 async submit(){this.busy=true;this.message='';try{const client=await this.clinics.management();if(!this.verified){const {error}=await client.auth.signUp({email:this.email,password:this.password,options:{captchaToken:this.captchaToken,emailRedirectTo:location.origin+'/auth/registration',data:{clinic_name:this.name,clinic_code:this.code,owner_name:this.owner}}});if(error)throw error;this.password='';this.message='E-postanızdaki doğrulama bağlantısını açın; ardından klinik başvurusunu tamamlayın.';}else{const {error}=await client.rpc('register_clinic',{p_name:this.name,p_code:this.code,p_owner:this.owner});if(error)throw error;await this.refresh();}}catch(e){this.message=e.message;}finally{this.busy=false;}}
 async refresh(){try{const {data,error}=await (await this.clinics.management()).from('clinic_applications').select('id,clinic_name,code,state,trial_ends_at,paid,safe_error').maybeSingle();if(error)throw error;this.application=data;}catch(e){this.message=e.message;}}
 stateLabel(state:string){return ({waitlisted:'Başvurunuz bekleme listesinde. Kapasite açıldığında kurulum başlayacak.',queued:'Kurulum sıraya alındı.',creating:'Klinik altyapısı hazırlanıyor.',waiting:'Klinik altyapısı hazırlanıyor.',schema:'Klinik veritabanı hazırlanıyor.',functions:'Klinik hizmetleri hazırlanıyor.',owner:'Klinik hesabı hazırlanıyor.',ready:'Kliniğiniz hazır.',attention:'Kurulum için Odivon ekibinin müdahalesi gerekiyor.'} as any)[state]||state;}
}
''',encoding='utf-8')
p=root/'src/app/app.routing.ts';s=p.read_text();s=s.replace("export const appRoutes: Route[] = [", "export const appRoutes: Route[] = [\n {path:'auth/sign-up',pathMatch:'full',redirectTo:'auth/registration'},")
p.write_text(s,encoding='utf-8')
